### ISSUE TITLE
Ctags cannot open tag file : Permission denied

### ISSUE THREAD

**Issue by Aaronzinhoo** [damon-kwok/modern-sh#4]
* **Version**: 27.2
* **Platform**: WSL2 Ubuntu 20.04

I dont this is a bug per this package, but I have not used ctags before and do not know where this could be trying to access. I am getting the error  `ctags:ctags: cannot open tag file : Permission denied` when I am saving a shell script. Hopefully you can point me in the right direction and thank you for the great package!

**Comment by damon-kwok** [comment]
I think ctags does not have permission to write files in your current directory.
